/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(preamble_correlation.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(7fff6f1e44577be27a30b970599c836d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/mode_s_decode/preamble_correlation.h>
// pydoc.h is automatically generated in the build directory
#include <preamble_correlation_pydoc.h>

void bind_preamble_correlation(py::module& m)
{

    using preamble_correlation    = gr::mode_s_decode::preamble_correlation;


    py::class_<preamble_correlation, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<preamble_correlation>>(m, "preamble_correlation", D(preamble_correlation))

        .def(py::init(&preamble_correlation::make),
           D(preamble_correlation,make)
        )
        



        ;




}








