/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-mode_s_decode
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_MODE_S_DECODE_API_H
#define INCLUDED_MODE_S_DECODE_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_mode_s_decode_EXPORTS
#define MODE_S_DECODE_API __GR_ATTR_EXPORT
#else
#define MODE_S_DECODE_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_MODE_S_DECODE_API_H */
